version: "3"

services:
  # Necessário executar um FLUSH PRIVILEGES no bash do mysql;
  mysql:
    image: mysql:5.7
    container_name: "${DB_CONTAINER_NAME}"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      TZ: "America/Sao_Paulo"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - "db_volume:${VOLUME_PATH}"
    env_file:
      - .env

volumes:
  db_volume:
    external: false